version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db_test
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test_network

volumes:
  postgres_data:

networks:
  test_network:
